language: go

go:
  - 1.19
env:
  global:
    - GOPROXY="https://proxy.golang.org"
    - GO111MODULE=on
    - DATABASE_URL="postgres://postgres@localhost/travis_ci_test?sslmode=disable"
dist: trusty
sudo: false
addons:
  postgresql: 9.6
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - go vet ./...
  - go install golang.org/x/lint/golint@latest
  - golint ./...
  - go install honnef.co/go/tools/cmd/staticcheck@latest
  - staticcheck -go 1.19 ./...
  - go build .
  - go test -v ./...
